- .github/CODEOWNERS
- .github/workflows/release.yml
Adding a new CODEOWNERS file to increase our release GPG key security. I'm also adding @augustuswm and @inickles so that I am not the sole "codeowner"
> Add codeowners file and edit release workflow

- docs/data-sources/oxide_ssh_key.md
- docs/resources/oxide_ssh_key.md
- internal/provider/data_source_ssh_key.go
- internal/provider/data_source_ssh_key_test.go
- internal/provider/provider.go
- internal/provider/resource_ssh_key.go
- internal/provider/resource_ssh_key_test.go
This pull request implements a new `oxide_ssh_key` resource and data source.
When I was using an Oxide rack with Terraform a few weeks ago I noticed that there was no support for an SSH key resource. Instead, I had to manually create an SSH key either using the UI, API, or CLI.
> Implement `oxide_ssh_key` resource and data source

- .changelog/0.1.0.toml
- docs/resources/oxide_project.md
- docs/resources/oxide_vpc.md
- internal/provider/resource_project.go
- internal/provider/resource_vpc.go
Closes: https://github.com/oxidecomputer/terraform-provider-oxide/issues/224
> Automatically remove system created VPC and subnet when deleting projects and VPCs

- .changelog/0.4.0.toml
- internal/provider/resource_vpc_firewall_rules.go
- internal/provider/resource_vpc_firewall_rules_test.go
This commit makes it possible to omit `filters.hosts`, `filters.ports` and `filters.protocols` for each firewall rule.
Unfortunately, a side effect of this change is that setting these attributes as empty arrays will no longer be supported. Initially, I intended to keep both but there are a few Terraform quirks that make this non-viable:
- Terraform differentiates between empty and nil, this means that I can't just set one or the other fully.
- I can't use a plan modifier to make Terraform believe null is the same as empty and correctly apply the plan without errors, but will always report a plan change when running `terraform plan`.
- I can't use a default value of empty array on nil, for the same reason as above.
- Sets are unordered lists, so I can't just copy values in order from the …
> Do not support empty arrays for filters

- go.mod
- go.sum
Ran acceptance tests manually against colo rack
```console
=== RUN   TestAccCloudDataSourceImage_full
=== PAUSE TestAccCloudDataSourceImage_full
=== RUN   TestAccCloudDataSourceImages_project
=== PAUSE TestAccCloudDataSourceImages_project
=== RUN   TestAccCloudDataSourceImages_silo
=== PAUSE TestAccCloudDataSourceImages_silo
=== RUN   TestAccCloudDataSourceInstanceExternalIPs_full
=== PAUSE TestAccCloudDataSourceInstanceExternalIPs_full
=== RUN   TestAccCloudDataSourceProject_full
=== PAUSE TestAccCloudDataSourceProject_full
=== RUN   TestAccCloudDataSourceProjects_full
=== PAUSE TestAccCloudDataSourceProjects_full
=== RUN   TestAccCloudDataSourceSSHKey_full
=== PAUSE TestAccCloudDataSourceSSHKey_full
=== RUN   TestAccCloudDataSourceVPCSubnet_full
=== …
```
> Bump go SDK to v0.1.0-beta7

- .changelog/0.4.0.toml
- docs/resources/oxide_ip_pool.md
- internal/provider/provider.go
- internal/provider/resource_ip_pool.go
- internal/provider/resource_ip_pool_test.go
```HCL
resource "oxide_ip_pool" "test" {
description       = "a new description for ip_pool"
name              = "myippool"
ranges = [
{
first_address = "172.20.15.227"
last_address  = "172.20.15.230"
},
{
first_address = "172.20.15.231"
last_address  = "172.20.15.239"
}
]
}
```
```console
$ TEST_ACC_NAME=TestAccResourceIpPool_full make testacc
=== RUN   TestAccResourceIpPool_full
=== PAUSE TestAccResourceIpPool_full
=== CONT  TestAccResourceIpPool_full
--- PASS: TestAccResourceIpPool_full (2.92s)
PASS
ok  	github.com/oxidecomputer/terraform-provider-oxide/internal/provider	2.926s
```
Closes: https://github.com/oxidecomputer/terraform-provider-oxide/issues/335
> IP pools resource

- .goreleaser.yml
Following update instructions here https://goreleaser.com/blog/goreleaser-v2/
Related: https://github.com/oxidecomputer/terraform-provider-oxide/pull/324
> Update goreleaser version to 2

- examples/instance_resource/instance.tf
A customer reported that the exmaple was missing a declaration of the instance external ip data. They identified the missing part which I inserted in this PR. I was able to verify the fix by deploying it against an internal rack.
> Fix example on returning instance external ip

- .github/CODEOWNERS
This patch adds Matthew Sanabria (`@sudomateo`) to `CODEOWNERS` and removes those who have served their time.
> codeowners: update owners

- .changelog/0.6.0.toml
- docs/resources/oxide_instance.md
- go.mod
- go.sum
- internal/provider/resource_instance.go
- internal/provider/resource_instance_test.go
Updates the provider to include the new memory and ncpu update functionality.
```console
$ make testacc
=== RUN   TestAccCloudResourceInstance_update
=== PAUSE TestAccCloudResourceInstance_update
=== CONT  TestAccCloudResourceInstance_update
--- PASS: TestAccCloudResourceInstance_update (64.81s)
PASS
ok  	github.com/oxidecomputer/terraform-provider-oxide/internal/provider	65.317s
```
> Update to Go SDK eb153ea

- .changelog/0.7.0.toml
- docs/data-sources/oxide_vpc_router.md
- docs/resources/oxide_vpc_router.md
- internal/provider/data_source_vpc_router.go
- internal/provider/data_source_vpc_router_test.go
- internal/provider/provider.go
- internal/provider/resource_vpc_router.go
- internal/provider/resource_vpc_router_test.go
This commit introduces the `oxide_vpc_router` resource and datasource.
Tested against the colo rack:
```console
$ TEST_ACC_NAME=TestAccCloudDataSourceVPCRouter_full make testacc
=== RUN   TestAccCloudDataSourceVPCRouter_full
=== PAUSE TestAccCloudDataSourceVPCRouter_full
=== CONT  TestAccCloudDataSourceVPCRouter_full
--- PASS: TestAccCloudDataSourceVPCRouter_full (1.67s)
PASS
ok  	github.com/oxidecomputer/terraform-provider-oxide/internal/provider	1.983s
$ TEST_ACC_NAME=TestAccCloudResourceVPCRouter_full make testacc
=== RUN   TestAccCloudResourceVPCRouter_full
=== PAUSE TestAccCloudResourceVPCRouter_full
=== CONT  TestAccCloudResourceVPCRouter_full
--- PASS: TestAccCloudResourceVPCRouter_full (7.73s)
PASS
ok …
```
> New oxide_vpc_router resource and datasource

- .goreleaser.yml
As per https://goreleaser.com/deprecations/#archivesformat
> Update GoReleaser deprecated fields

- docs/resources/oxide_vpc_firewall_rules.md
Updated the documentation to address the following points.
* Mention that rules are exhaustive and will overwrite existing rules.
* Describe how to specify port ranges for the `ports` attribute.
Closes https://github.com/oxidecomputer/terraform-provider-oxide/issues/404.
> vpc_firewall_rules: update documentation

- go.mod
- go.sum
- internal/provider/data_source_images.go
- internal/provider/data_source_projects.go
- internal/provider/resource_instance.go
- internal/provider/resource_ip_pool.go
- internal/provider/resource_ip_pool_silo_link.go
- internal/provider/resource_ip_pool_silo_link_test.go
- internal/provider/resource_vpc_firewall_rules.go
- internal/provider/resource_vpc_firewall_rules_test.go
Depends on https://github.com/oxidecomputer/oxide.go/pull/274
Closes: #403 
Ran acceptance tests against the colo rack
```console
$ make testacc
=== RUN   TestAccCloudDataSourceImage_full
=== PAUSE TestAccCloudDataSourceImage_full
=== RUN   TestAccCloudDataSourceImages_project
=== PAUSE TestAccCloudDataSourceImages_project
=== RUN   TestAccCloudDataSourceImages_silo
=== PAUSE TestAccCloudDataSourceImages_silo
=== RUN   TestAccCloudDataSourceInstanceExternalIPs_full
=== PAUSE TestAccCloudDataSourceInstanceExternalIPs_full
=== RUN   TestAccCloudDataSourceProject_full
=== PAUSE TestAccCloudDataSourceProject_full
=== RUN   TestAccCloudDataSourceProjects_full
=== PAUSE TestAccCloudDataSourceProjects_full
=== RUN   TestAccCloudDataSourceSSHKey_full
=== …
```
> Bump SDK version to c8be658

- .changelog/0.8.0.toml
- docs/data-sources/oxide_anti_affinity_group.md
- docs/resources/oxide_anti_affinity_group.md
- go.mod
- go.sum
- internal/provider/data_source_anti_affinity_group.go
- internal/provider/data_source_anti_affinity_group_test.go
- internal/provider/provider.go
- internal/provider/resource_anti_affinity_group.go
- internal/provider/resource_anti_affinity_group_test.go
Depends on https://github.com/oxidecomputer/oxide.go/pull/276
Closes: https://github.com/oxidecomputer/terraform-provider-oxide/issues/416
Tested against the dogfood rack
```console
$ TEST_ACC_NAME=TestAccCloudResourceAntiAffinityGroup_full make testacc
=== RUN   TestAccCloudResourceAntiAffinityGroup_full
=== PAUSE TestAccCloudResourceAntiAffinityGroup_full
=== CONT  TestAccCloudResourceAntiAffinityGroup_full
--- PASS: TestAccCloudResourceAntiAffinityGroup_full (4.44s)
PASS
ok  	github.com/oxidecomputer/terraform-provider-oxide/internal/provider	4.771s
```
```console
$ TEST_ACC_NAME=TestAccCloudDataSourceAntiAffinityGroup_full make testacc
=== RUN   TestAccCloudDataSourceAntiAffinityGroup_full
=== PAUSE …
```
> New anti-affinity group resource and datasource

- .changelog/0.8.0.toml
- docs/resources/oxide_instance.md
- go.mod
- internal/provider/resource_instance.go
- internal/provider/resource_instance_test.go
- internal/provider/utils.go
- internal/provider/utils_test.go
Depends on https://github.com/oxidecomputer/oxide.go/pull/276
Closes: https://github.com/oxidecomputer/terraform-provider-oxide/issues/411
Tested against dogfood rack
```console
$ TEST_ACC_NAME=TestAccCloudResourceInstance make testacc
=== RUN   TestAccCloudResourceInstance_full
=== PAUSE TestAccCloudResourceInstance_full
=== RUN   TestAccCloudResourceInstance_extIPs
=== PAUSE TestAccCloudResourceInstance_extIPs
=== RUN   TestAccCloudResourceInstance_sshKeys
=== PAUSE TestAccCloudResourceInstance_sshKeys
=== RUN   TestAccCloudResourceInstance_nic
=== PAUSE TestAccCloudResourceInstance_nic
=== RUN   TestAccCloudResourceInstance_disk
=== PAUSE TestAccCloudResourceInstance_disk
=== RUN   TestAccCloudResourceInstance_update
=== PAUSE …
```
> Anti-affinity groups on instance create

- README.md
- docs/index.md
- examples/demo/demo.tf
- examples/disk_resource/disk.tf
- examples/instance_resource/instance.tf
- examples/vpc_resource/vpc.tf
- go.mod
- go.sum
Tested against the colo rack
```console
make testacc
=== RUN   TestAccCloudDataSourceAntiAffinityGroup_full
=== PAUSE TestAccCloudDataSourceAntiAffinityGroup_full
=== RUN   TestAccCloudDataSourceImage_full
=== PAUSE TestAccCloudDataSourceImage_full
=== RUN   TestAccCloudDataSourceImages_project
=== PAUSE TestAccCloudDataSourceImages_project
=== RUN   TestAccCloudDataSourceImages_silo
=== PAUSE TestAccCloudDataSourceImages_silo
=== RUN   TestAccCloudDataSourceInstanceExternalIPs_full
=== PAUSE TestAccCloudDataSourceInstanceExternalIPs_full
=== RUN   TestAccCloudDataSourceProject_full
=== PAUSE TestAccCloudDataSourceProject_full
=== RUN   TestAccCloudDataSourceProjects_full
=== PAUSE TestAccCloudDataSourceProjects_full
=== RUN …
```
> Update SDK to v0.4.0 and doc fixes

- .changelog/0.9.0.toml
- docs/data-sources/oxide_floating_ip.md
- docs/resources/oxide_floating_ip.md
- internal/provider/data_source_floating_ip.go
- internal/provider/data_source_floating_ip_test.go
- internal/provider/provider.go
- internal/provider/resource_anti_affinity_group_test.go
- internal/provider/resource_floating_ip.go
- internal/provider/resource_floating_ip_test.go
Added the `oxide_floating_ip` resource and data source. This allows managing and reading an Oxide floating IP.
Closes #257.
> oxide_floating_ip: initial resource and data source

- internal/provider/resource_instance.go
- internal/provider/resource_instance_test.go
Closes https://github.com/oxidecomputer/terraform-provider-oxide/issues/378.
This patch updates the `oxide_instance` resource to support in-place modifications to its `external_ips` attribute. That is, the instance will no longer be destroyed and recreated when `external_ips` is modified. Instead, the instance will be stopped, external IPs will be detached and/or attached, and the instance will be started.
This patch also updates the `Read` method to refresh the external IPs attached to the instance. Previously, since the external IPs required a resource replacement there was no need to refresh them.
There are 2 types of external IPs, ephemeral and floating. There can be at most 1 ephemeral external IP attached to an instance and any number of floating external IPs. That means in order to …
> oxide_instance: allow in-place `external_ips` modification

- .changelog/0.10.0.toml
- internal/provider/resource_instance.go
Add validation to the `ssh_public_keys` attribute to validate that it contains no empty or null values. A customer pointed out that the following Terraform configuration resulted in an unclear error message.
```hcl
resource "oxide_instance" "example" {
ssh_public_keys = ["4db0f0d3-8e82-491a-beff-39764be1c529", null]
}
```
Even worse, the error message didn't occur until apply time.
```
oxide_instance.example: Creating...
╷
│ Error: Error retrieving name or ID information
│
│   with oxide_instance.example,
│   on main.tf line 22, in resource "oxide_instance" "example":
│   22: resource "oxide_instance" "example" {
│
│ name or ID parse error: invalid syntax
╵
```
With this change, the error message occurs at plan time and is much more clear.
```
> terraform apply
╷
│ Error: Null Set Value
│ …
```
> oxide_instance: add validation to ssh_public_keys attribute

- go.mod
- go.sum
I tested all of the cloud endpoints against the dogfood rack and everything is working as expected
```console
$ make testacc
=== RUN   TestAccCloudDataSourceAntiAffinityGroup_full
=== PAUSE TestAccCloudDataSourceAntiAffinityGroup_full
=== RUN   TestAccCloudDataSourceFloatingIP_full
=== PAUSE TestAccCloudDataSourceFloatingIP_full
=== RUN   TestAccCloudDataSourceImage_full
=== PAUSE TestAccCloudDataSourceImage_full
=== RUN   TestAccCloudDataSourceImages_project
=== PAUSE TestAccCloudDataSourceImages_project
=== RUN   TestAccCloudDataSourceImages_silo
=== PAUSE TestAccCloudDataSourceImages_silo
=== RUN   TestAccCloudDataSourceInstanceExternalIPs_full
=== PAUSE TestAccCloudDataSourceInstanceExternalIPs_full
=== RUN   TestAccCloudDataSourceProject_full
=== …
```
> Update to Go SDK v0.5.0

- internal/provider/resource_instance.go
If the anti-affinity group has already been removed, the instance resource shouldn't care about a 404 when removing membership from it.
Also, this commit changes the error messages to make it clearer that we're not actually trying to delete the anti-affinity group. Just removing the instance's membership.
Tested against the colo rack with @askfongjojo's HCL config from https://github.com/oxidecomputer/terraform-provider-oxide/issues/446.
Applying first:
```hcl
resource "oxide_anti_affinity_group" "peers" {
project_id  = data.oxide_project.proj.id
description = "another anti-affinity group"
name        = "related-peers"
policy      = "allow"
}
resource "oxide_instance" "test" {
project_id      = data.oxide_project.proj.id
description     = "a test instance"
name            = "test" …
```
> Ignore 404 when removing instance membership from anti-affinity group

- internal/provider/resource_vpc_firewall_rules_test.go
Added acceptance tests to surface the issue reported in https://github.com/oxidecomputer/terraform-provider-oxide/issues/453.
See https://github.com/oxidecomputer/terraform-provider-oxide/issues/453#issuecomment-2992788470 for an understanding of what's happening.
> vpc_firewall_rules: fix provider produced invalid plan

- README.md
- docs/index.md
- examples/demo/demo.tf
- examples/disk_resource/disk.tf
- examples/instance_resource/instance.tf
- examples/vpc_resource/vpc.tf
Updated the version constraint in preparation for release v0.12.0 in https://github.com/oxidecomputer/terraform-provider-oxide/issues/462.
> misc: update version constraint

- CHANGELOG.md
Generated the changelog in preparation for release v0.12.0 in https://github.com/oxidecomputer/terraform-provider-oxide/issues/462.
> misc: generate changelog for v0.12.0

- .changelog/0.13.0.toml
- docs/resources/oxide_vpc_firewall_rules.md
- go.mod
- go.sum
- internal/provider/resource_vpc_firewall_rules.go
- internal/provider/resource_vpc_firewall_rules_test.go
Pulled in the Go SDK changes from
https://github.com/oxidecomputer/oxide.go/pull/304 which contained changes to the VPC firewall rules APIs.
Updated the `oxide_vpc_firewall_rules` resource to account for these changes.
> resource(vpc_firewall_rules): support new api changes

- internal/provider/resource_instance.go
Updated the `oxide_instance` resource to use the floating IP ID for floating external IPs instead of the IP pool ID. Without this change, Terraform will be unable to detach a floating IP from an instance since it will try to detach using the floating IP IP pool ID instead of the floating IP ID itself.
> resource(instance): use floating ip id instead of ip pool id

- .changelog/0.14.0.toml
- internal/provider/resource_silo.go
Related to https://github.com/oxidecomputer/omicron/issues/8973.
The `oxide_silo` resource no longer accepts negative values for `quotas.cpus`. When a negative value is given, Terraform errors with the following.
```
╷
│ Error: Invalid Attribute Value
│
│   with oxide_silo.example,
│   on main.tf line 39, in resource "oxide_silo" "example":
│   39: resource "oxide_silo" "example" {
│
│ Attribute quotas.cpus value must be at least 0, got: -2
╵
```
> silo: do not allow negative cpu quotas

- .changelog/0.15.0.toml
I forgot to update the changelog in https://github.com/oxidecomputer/terraform-provider-oxide/pull/529.
> misc: update changelog
